# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shedcur', models.FloatField()),
                ('outscur', models.FloatField()),
                ('gpuavg', models.IntegerField(blank=True, null=True)),
                ('gpuhigh', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
