# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('avgshed', models.FloatField(null=True)),
                ('highshed', models.FloatField(null=True)),
                ('avgouts', models.FloatField(null=True)),
                ('highouts', models.FloatField(null=True)),
                ('avggpu', models.IntegerField(null=True)),
                ('highgpu', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='gpuavg',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='gpuhigh',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
    ]
