# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_auto_20180412_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='avggpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='avgouts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='avgshed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='highgpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='highouts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='highshed',
            field=models.FloatField(),
        ),
    ]
