# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.AddField(
            model_name='history',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='history',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
