# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0005_auto_20180418_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
