# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_auto_20180423_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('wtm', models.IntegerField()),
                ('cmc', models.IntegerField()),
                ('polo', models.CharField(max_length=100)),
                ('grav', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('abv', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('nethash', models.FloatField()),
                ('blockr', models.FloatField()),
                ('blockt', models.FloatField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
