# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-07 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0008_coins_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='algo',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='algo',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
