# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0009_auto_20180606_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='cbri',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
