# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0010_coins_cbri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='grav',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='coins',
            name='polo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
