# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0011_auto_20180606_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='decimal',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='coins',
            name='profit',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='coins',
            name='scroll',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
